function GenCodeMainAll
% Code Generator
fidp = fopen( 'MainProto.c', 'w' );
fidc = fopen( 'MainCode.c', 'w' );
fidm = fopen( 'MainMenu.c', 'w' );
fprintf( fidp, '//===========================================\n' );
fprintf( fidp, '//// Script-generated code - do not edit ////\n' );
fprintf( fidp, '//===========================================\n' );
fprintf( fidc, '//===========================================\n' );
fprintf( fidc, '//// Script-generated code - do not edit ////\n' );
fprintf( fidc, '//===========================================\n' );
fprintf( fidm, '//===========================================\n' );
fprintf( fidm, '//// Script-generated code - do not edit ////\n' );
fprintf( fidm, '//===========================================\n' );
fprintf( fidp, '//=============\n' );
fprintf( fidp, '// TxAXISource\n' );
fprintf( fidp, '//=============\n' );
fprintf( fidc, '//=============\n' );
fprintf( fidc, '// TxAXISource\n' );
fprintf( fidc, '//=============\n' );
GenCodeMain( 'TxAXISource'         , fidc, fidp, fidm,  'Bram' , true , true , true , true , true , true , true , 'Axs' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Axs' );
fprintf( fidp, '//================\n' );
fprintf( fidp, '// TxSourceBramC\n' );
fprintf( fidp, '//================\n' );
fprintf( fidc, '//===============\n' );
fprintf( fidc, '// TxSourceBramC\n' );
fprintf( fidc, '//===============\n' );
GenCodeMain( 'TxSourceAXIBramC'    , fidc, fidp, fidm,  'Bram' , true , true , true , true , true , true , false, 'Brc' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Brc' );
fprintf( fidp, '//========\n' );
fprintf( fidp, '// TxFFTC\n' );
fprintf( fidp, '//========\n' );
fprintf( fidc, '//========\n' );
fprintf( fidc, '// TxFFTC\n' );
fprintf( fidc, '//========\n' );
GenCodeMain( 'TxFFTC'              , fidc, fidp, fidm,  ''     , true , false, false, false, false, false, false, 'Txf' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Txf' );
fprintf( fidp, '//===========\n' );
fprintf( fidp, '// RxNsdFFTC\n' );
fprintf( fidp, '//===========\n' );
fprintf( fidc, '//===========\n' );
fprintf( fidc, '// RxNsdFFTC\n' );
fprintf( fidc, '//===========\n' );
GenCodeMain( 'RxNsdFFTC'           , fidc, fidp, fidm,  ''     , true , false, false, false, false, false, false, 'Nsf' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Nsf' );
fprintf( fidp, '//=========\n' );
fprintf( fidp, '// TxTSInj\n' );
fprintf( fidp, '//=========\n' );
fprintf( fidc, '//=========\n' );
fprintf( fidc, '// TxTSInj\n' );
fprintf( fidc, '//=========\n' );
GenCodeMain( 'TxTSInj'             , fidc, fidp, fidm,  'TsBuf', false, true , true , true , true , true , true , 'Tsi' );
GenCodeMain( 'TxTSInj'             , fidc, fidp, fidm,  'TxBuf', false, true , true , false, false, false, true , 'Tsi');
GenCodeMain( 'TxTSInj'             , fidc, fidp, fidm,  'RxBuf', false, true , false, true , true , false, false, 'Tsi' );
GenCodeMain( 'TxTSInj'             , fidc, fidp, fidm,  'PsBuf', true , true , true , false, false, false, true , 'Tsi' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Tsi' );
fprintf( fidp, '//==============\n' );
fprintf( fidp, '// RFChanTREmul\n' );
fprintf( fidp, '//==============\n' );
fprintf( fidc, '//==============\n' );
fprintf( fidc, '// RFChanTREmul\n' );
fprintf( fidc, '//==============\n' );
GenCodeMain( 'RFChanTREmul'        , fidc, fidp, fidm,  'PsLUT', false, true , true , true,  true , true , true , 'Emu' );
GenCodeMain( 'RFChanTREmul'        , fidc, fidp, fidm,  'HwLUT', true , true , true , true , true , true , true , 'Emu' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Emu' );
fprintf( fidp, '//================\n' );
fprintf( fidp, '// RFChanTREmulSw\n' );
fprintf( fidp, '//================\n' );
fprintf( fidc, '//================\n' );
fprintf( fidc, '// RFChanTREmulSw\n' );
fprintf( fidc, '//================\n' );
GenCodeMain( 'RFChanTREmulSw'      , fidc, fidp, fidm,  ''     , true , false, false, false, false, false, false, 'Ems' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Ems' );
fprintf( fidp, '//=====================\n' );
fprintf( fidp, '// RFChanTREmulFreqCtr\n' );
fprintf( fidp, '//=====================\n' );
fprintf( fidc, '//=====================\n' );
fprintf( fidc, '// RFChanTREmulFreqCtr\n' );
fprintf( fidc, '//=====================\n' );
GenCodeMain( 'RFChanTREmulFreqCtr' , fidc, fidp, fidm,  ''     , true , false, false, false, false, false, false, 'Emf' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Emf' );
fprintf( fidp, '//==================\n' );
fprintf( fidp, '// AD9364ClkFreqCtr\n' );
fprintf( fidp, '//==================\n' );
fprintf( fidc, '//==================\n' );
fprintf( fidc, '// AD9364ClkFreqCtr\n' );
fprintf( fidc, '//==================\n' );
GenCodeMain( 'AD9364ClkFreqCtr'    , fidc, fidp, fidm,  ''     , true , false, false, false, false, false, false, 'Acf' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Acf' );
fprintf( fidp, '//==================\n' );
fprintf( fidp, '// AD9364DACFreqCtr\n' );
fprintf( fidp, '//==================\n' );
fprintf( fidc, '//==================\n' );
fprintf( fidc, '// AD9364DACFreqCtr\n' );
fprintf( fidc, '//==================\n' );
GenCodeMain( 'AD9364DACFreqCtr'    , fidc, fidp, fidm,  ''     , true , false, false, false, false, false, false, 'Adf' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Adf' );
fprintf( fidp, '//==================\n' );
fprintf( fidp, '// AD9364ADCFreqCtr\n' );
fprintf( fidp, '//==================\n' );
fprintf( fidc, '//==================\n' );
fprintf( fidc, '// AD9364ADCFreqCtr\n' );
fprintf( fidc, '//==================\n' );
GenCodeMain( 'AD9364ADCFreqCtr'    , fidc, fidp, fidm,  ''     , true , false, false, false, false, false, false, 'Aaf' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Aaf' );
fprintf( fidp, '//=============\n' );
fprintf( fidp, '// RxNSDet    \n' );
fprintf( fidp, '//=============\n' );
fprintf( fidc, '//=============\n' );
fprintf( fidc, '// RxNSDet    \n' );
fprintf( fidc, '//=============\n' );
GenCodeMain( 'RxNSDet'             , fidc, fidp, fidm,  ''     , true , false, false, false, false, false, false, 'Nsd');
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Nsd' );
fprintf( fidp, '//==============\n' );
fprintf( fidp, '// RxTddAXISink\n' );
fprintf( fidp, '//==============\n' );
fprintf( fidc, '//==============\n' );
fprintf( fidc, '// RxTddAxiSink\n' );
fprintf( fidc, '//==============\n' );
GenCodeMain( 'RxTddAXISink'        , fidc, fidp, fidm,  'Bram' , true , true , true , true , true , false, true , 'Dsk');
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Dsk' );
fprintf( fidp, '//==============\n' );
fprintf( fidp, '// RxPrsAXISink\n' );
fprintf( fidp, '//==============\n' );
fprintf( fidc, '//==============\n' );
fprintf( fidc, '// RxPrsAxiSink\n' );
fprintf( fidc, '//==============\n' );
GenCodeMain( 'RxPrsAXISink'        , fidc, fidp, fidm,  'Bram' , true , true , true , true , true , false, true , 'Prs');
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Prs' );
fprintf( fidp, '//==============\n' );
fprintf( fidp, '// RxDtaAXISink\n' );
fprintf( fidp, '//==============\n' );
fprintf( fidc, '//==============\n' );
fprintf( fidc, '// RxDtaAxiSink\n' );
fprintf( fidc, '//==============\n' );
GenCodeMain( 'RxDtaAXISink'        , fidc, fidp, fidm,  'Bram' , true , true , true , true , true , false, true , 'Dta');
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Dta' );
fprintf( fidp, '//=================\n' );
fprintf( fidp, '// RxNsdA00AXISink\n' );
fprintf( fidp, '//=================\n' );
fprintf( fidc, '//=================\n' );
fprintf( fidc, '// RxNsdA00AxiSink\n' );
fprintf( fidc, '//=================\n' );
GenCodeMain( 'RxNsdA00AXISink'     , fidc, fidp, fidm,  'Bram' , true , true , true , true , true , false, true , 'A00');
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'A00' );
fprintf( fidp, '//=================\n' );
fprintf( fidp, '// RxNsdA01AXISink\n' );
fprintf( fidp, '//=================\n' );
fprintf( fidc, '//=================\n' );
fprintf( fidc, '// RxNsdA01AxiSink\n' );
fprintf( fidc, '//=================\n' );
GenCodeMain( 'RxNsdA01AXISink'     , fidc, fidp, fidm,  'Bram' , true , true , true , true , true , false, true , 'A01');
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'A01' );
fprintf( fidp, '//=================\n' );
fprintf( fidp, '// RxNsdA15AXISink\n' );
fprintf( fidp, '//=================\n' );
fprintf( fidc, '//=================\n' );
fprintf( fidc, '// RxNsdA15AxiSink\n' );
fprintf( fidc, '//=================\n' );
GenCodeMain( 'RxNsdA15AXISink'     , fidc, fidp, fidm,  'Bram' , true , true , true , true , true , false, true , 'A15');
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'A15');
fprintf( fidp, '//====================\n' );
fprintf( fidp, '// RxNsdCordicAXISink\n' );
fprintf( fidp, '//====================\n' );
fprintf( fidc, '//====================\n' );
fprintf( fidc, '// RxNsdCordicAXISink\n' );
fprintf( fidc, '//====================\n' );
GenCodeMain( 'RxNsdCordicAXISink'  , fidc, fidp, fidm,  'Bram' , true , true , true , true , true , false, true , 'Csk' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Csk' );
fprintf( fidp, '//=================\n' );
fprintf( fidp, '// RxNsdFFTAXISink\n' );
fprintf( fidp, '//=================\n' );
fprintf( fidc, '//=================\n' );
fprintf( fidc, '// RxNsdFFTAXISink\n' );
fprintf( fidc, '//=================\n' );
GenCodeMain( 'RxNsdFFTAXISink'     , fidc, fidp, fidm,  'Bram' , true , true , true , true , true , false, true , 'Fsk' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'Fsk' );
fprintf( fidp, '//====================\n' );
fprintf( fidp, '// RxNsdBcast00AXISink\n' );
fprintf( fidp, '//====================\n' );
fprintf( fidc, '//====================\n' );
fprintf( fidc, '// RxNsdBcast00AXISink\n' );
fprintf( fidc, '//====================\n' );
GenCodeMain( 'RxNsdB00AXISink'     , fidc, fidp, fidm,  'Bram' , true , true , true , true , true , false, true , 'B00' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'B00' );
fprintf( fidp, '//====================\n' );
fprintf( fidp, '// RxNsdBcast01AXISink\n' );
fprintf( fidp, '//====================\n' );
fprintf( fidc, '//====================\n' );
fprintf( fidc, '// RxNsdBcast01AXISink\n' );
fprintf( fidc, '//====================\n' );
GenCodeMain( 'RxNsdB01AXISink'     , fidc, fidp, fidm,  'Bram' , true , true , true , true , true , false, true , 'B01' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'B01' );
fprintf( fidp, '//====================\n' );
fprintf( fidp, '// RxNsdBcast15AXISink\n' );
fprintf( fidp, '//====================\n' );
fprintf( fidc, '//====================\n' );
fprintf( fidc, '// RxNsdBcast15AXISink\n' );
fprintf( fidc, '//====================\n' );
GenCodeMain( 'RxNsdB15AXISink'     , fidc, fidp, fidm,  'Bram' , true , true , true , true , true , false, true , 'B15' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'B15' );
fprintf( fidp, '//=======\n' );
fprintf( fidp, '// PrsCIR\n' );
fprintf( fidp, '//=======\n' );
fprintf( fidc, '//=======\n' );
fprintf( fidc, '// PrsCIR\n' );
fprintf( fidc, '//=======\n' );
GenCodeMain( 'RxPrsCIR'            , fidc, fidp, fidm,  'BramFFT' , false, true , true , true , true , false, true , 'CIR' );
GenCodeMain( 'RxPrsCIR'            , fidc, fidp, fidm,  'BramABS' , true , true , true , true , true , false, true , 'CIR' );
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'CIR' );
fprintf( fidp, '//=======\n' );
fprintf( fidp, '// PrsBPA\n' );
fprintf( fidp, '//=======\n' );
fprintf( fidc, '//=======\n' );
fprintf( fidc, '// PrsBPA\n' );
fprintf( fidc, '//=======\n' );
GenCodeMain( 'RxPrsBPA'            , fidc, fidp, fidm,  ''     , true , false, false, false, false, false, false, 'BPA');
GenCodeMain( ''                    , fidc, fidp, fidm,  ''     , false, false, false, false, false, false, false, 'BPA' );
fprintf( fidp, '//===========================================\n' );
fprintf( fidp, '//////// End of script-generated code ///////\n' );
fprintf( fidp, '//===========================================\n' );
fprintf( fidc, '//===========================================\n' );
fprintf( fidc, '//////// End of script-generated code ///////\n' );
fprintf( fidc, '//===========================================\n' );
fprintf( fidm, '//===========================================\n' );
fprintf( fidm, '//////// End of script-generated code ///////\n' );
fprintf( fidm, '//===========================================\n' );

fclose( fidp );
fclose( fidc );
fclose( fidm );