//===========================================
//// Script-generated code - do not edit ////
//===========================================
    ( void ) shellRegisterCommand( &mainShell, "AXS"  , "AxsRBram"  ,  1, "<adr>                                   Read  TxAXISource Bram"                , mainReadTxAXISourceBram              );
    ( void ) shellRegisterCommand( &mainShell, "AXS"  , "AxsWBram"  ,  2, "<adr val>                               Write TxAXISource Bram"                , mainWriteTxAXISourceBram             );
    ( void ) shellRegisterCommand( &mainShell, "AXS"  , "AxsIBram"  ,  3, "<adr nwd val>                           Init  TxAXISource Bram"                , mainInitTxAXISourceBram              );
    ( void ) shellRegisterCommand( &mainShell, "AXS"  , "AxsLBram"  ,  0, "                                        Load  TxAXISource Bram"                , mainLoadTxAXISourceBram              );
    ( void ) shellRegisterCommand( &mainShell, "AXS"  , "AxsDBram"  ,  0, ""                                                                              , mainDumpTxAXISourceBram              );
    ( void ) shellRegisterCommand( &mainShell, "AXS"  , "AxsDBram"  ,  1, ""                                                                              , mainDumpTxAXISourceBram              );
    ( void ) shellRegisterCommand( &mainShell, "AXS"  , "AxsDBram"  ,  2, "[<adr nbit(0, 8-16)>]                   Dump  TxAXISource Bram"                , mainDumpTxAXISourceBram              );
    ( void ) shellRegisterCommand( &mainShell, "AXS"  , "AxsRslv"   ,  1, "<reg>                                   Read  TxAXISource Slv Reg"             , mainReadTxAXISourceSlvReg            );
    ( void ) shellRegisterCommand( &mainShell, "AXS"  , "AxsWslv"   ,  2, "<reg val>                               Write TxAXISource Slv Reg"             , mainWriteTxAXISourceSlvReg           );
    ( void ) shellRegisterCommand( &mainShell, "AXS"  , "AxsDslv"   ,  0, ""                                                                              , mainDumpTxAXISourceSlvReg            );
    ( void ) shellRegisterCommand( &mainShell, "AXS"  , "AxsDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  TxAXISource Slv Reg"             , mainDumpTxAXISourceSlvReg            );
    ( void ) shellRegisterCommand( &mainShell, "AXS"  , "AxsDmp"    ,  0, "                                        Dump  TxAXISource State"               , mainDumpTxAXISource                  );
    ( void ) shellRegisterCommand( &mainShell, "AXS"  , "AxsRst"    ,  0, "                                        Reset TxAXISource"                     , mainResetTxAXISource                 );
    ( void ) shellRegisterCommand( &mainShell, "AXS"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "BRC"  , "BrcRBram"  ,  1, "<adr>                                   Read  TxSourceAXIBramC Bram"           , mainReadTxSourceAXIBramCBram         );
    ( void ) shellRegisterCommand( &mainShell, "BRC"  , "BrcWBram"  ,  2, "<adr val>                               Write TxSourceAXIBramC Bram"           , mainWriteTxSourceAXIBramCBram        );
    ( void ) shellRegisterCommand( &mainShell, "BRC"  , "BrcIBram"  ,  3, "<adr nwd val>                           Init  TxSourceAXIBramC Bram"           , mainInitTxSourceAXIBramCBram         );
    ( void ) shellRegisterCommand( &mainShell, "BRC"  , "BrcLBram"  ,  0, "                                        Load  TxSourceAXIBramC Bram"           , mainLoadTxSourceAXIBramCBram         );
    ( void ) shellRegisterCommand( &mainShell, "BRC"  , "BrcRslv"   ,  1, "<reg>                                   Read  TxSourceAXIBramC Slv Reg"        , mainReadTxSourceAXIBramCSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "BRC"  , "BrcWslv"   ,  2, "<reg val>                               Write TxSourceAXIBramC Slv Reg"        , mainWriteTxSourceAXIBramCSlvReg      );
    ( void ) shellRegisterCommand( &mainShell, "BRC"  , "BrcDslv"   ,  0, ""                                                                              , mainDumpTxSourceAXIBramCSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "BRC"  , "BrcDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  TxSourceAXIBramC Slv Reg"        , mainDumpTxSourceAXIBramCSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "BRC"  , "BrcDmp"    ,  0, "                                        Dump  TxSourceAXIBramC State"          , mainDumpTxSourceAXIBramC             );
    ( void ) shellRegisterCommand( &mainShell, "BRC"  , "BrcRst"    ,  0, "                                        Reset TxSourceAXIBramC"                , mainResetTxSourceAXIBramC            );
    ( void ) shellRegisterCommand( &mainShell, "BRC"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "TXF"  , "TxfRslv"   ,  1, "<reg>                                   Read  TxFFTC Slv Reg"                  , mainReadTxFFTCSlvReg                 );
    ( void ) shellRegisterCommand( &mainShell, "TXF"  , "TxfWslv"   ,  2, "<reg val>                               Write TxFFTC Slv Reg"                  , mainWriteTxFFTCSlvReg                );
    ( void ) shellRegisterCommand( &mainShell, "TXF"  , "TxfDslv"   ,  0, ""                                                                              , mainDumpTxFFTCSlvReg                 );
    ( void ) shellRegisterCommand( &mainShell, "TXF"  , "TxfDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  TxFFTC Slv Reg"                  , mainDumpTxFFTCSlvReg                 );
    ( void ) shellRegisterCommand( &mainShell, "TXF"  , "TxfDmp"    ,  0, "                                        Dump  TxFFTC State"                    , mainDumpTxFFTC                       );
    ( void ) shellRegisterCommand( &mainShell, "TXF"  , "TxfRst"    ,  0, "                                        Reset TxFFTC"                          , mainResetTxFFTC                      );
    ( void ) shellRegisterCommand( &mainShell, "TXF"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "NSF"  , "NsfRslv"   ,  1, "<reg>                                   Read  RxNsdFFTC Slv Reg"               , mainReadRxNsdFFTCSlvReg              );
    ( void ) shellRegisterCommand( &mainShell, "NSF"  , "NsfWslv"   ,  2, "<reg val>                               Write RxNsdFFTC Slv Reg"               , mainWriteRxNsdFFTCSlvReg             );
    ( void ) shellRegisterCommand( &mainShell, "NSF"  , "NsfDslv"   ,  0, ""                                                                              , mainDumpRxNsdFFTCSlvReg              );
    ( void ) shellRegisterCommand( &mainShell, "NSF"  , "NsfDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxNsdFFTC Slv Reg"               , mainDumpRxNsdFFTCSlvReg              );
    ( void ) shellRegisterCommand( &mainShell, "NSF"  , "NsfDmp"    ,  0, "                                        Dump  RxNsdFFTC State"                 , mainDumpRxNsdFFTC                    );
    ( void ) shellRegisterCommand( &mainShell, "NSF"  , "NsfRst"    ,  0, "                                        Reset RxNsdFFTC"                       , mainResetRxNsdFFTC                   );
    ( void ) shellRegisterCommand( &mainShell, "NSF"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiRTsBuf" ,  1, "<adr>                                   Read  TxTSInj TsBuf"                   , mainReadTxTSInjTsBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiWTsBuf" ,  2, "<adr val>                               Write TxTSInj TsBuf"                   , mainWriteTxTSInjTsBuf                );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiITsBuf" ,  3, "<adr nwd val>                           Init  TxTSInj TsBuf"                   , mainInitTxTSInjTsBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiLTsBuf" ,  0, "                                        Load  TxTSInj TsBuf"                   , mainLoadTxTSInjTsBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiDTsBuf" ,  0, ""                                                                              , mainDumpTxTSInjTsBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiDTsBuf" ,  1, ""                                                                              , mainDumpTxTSInjTsBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiDTsBuf" ,  2, "[<adr nbit(0, 8-16)>]                   Dump  TxTSInj TsBuf"                   , mainDumpTxTSInjTsBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiRTxBuf" ,  1, "<adr>                                   Read  TxTSInj TxBuf"                   , mainReadTxTSInjTxBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiDTxBuf" ,  0, ""                                                                              , mainDumpTxTSInjTxBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiDTxBuf" ,  1, ""                                                                              , mainDumpTxTSInjTxBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiDTxBuf" ,  2, "[<adr nbit(0, 8-16)>]                   Dump  TxTSInj TxBuf"                   , mainDumpTxTSInjTxBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiWRxBuf" ,  2, "<adr val>                               Write TxTSInj RxBuf"                   , mainWriteTxTSInjRxBuf                );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiIRxBuf" ,  3, "<adr nwd val>                           Init  TxTSInj RxBuf"                   , mainInitTxTSInjRxBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiRPsBuf" ,  1, "<adr>                                   Read  TxTSInj PsBuf"                   , mainReadTxTSInjPsBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiDPsBuf" ,  0, ""                                                                              , mainDumpTxTSInjPsBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiDPsBuf" ,  1, ""                                                                              , mainDumpTxTSInjPsBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiDPsBuf" ,  2, "[<adr nbit(0, 8-16)>]                   Dump  TxTSInj PsBuf"                   , mainDumpTxTSInjPsBuf                 );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiRslv"   ,  1, "<reg>                                   Read  TxTSInj Slv Reg"                 , mainReadTxTSInjSlvReg                );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiWslv"   ,  2, "<reg val>                               Write TxTSInj Slv Reg"                 , mainWriteTxTSInjSlvReg               );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiDslv"   ,  0, ""                                                                              , mainDumpTxTSInjSlvReg                );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  TxTSInj Slv Reg"                 , mainDumpTxTSInjSlvReg                );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiDmp"    ,  0, "                                        Dump  TxTSInj State"                   , mainDumpTxTSInj                      );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , "TsiRst"    ,  0, "                                        Reset TxTSInj"                         , mainResetTxTSInj                     );
    ( void ) shellRegisterCommand( &mainShell, "TSI"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuRPsLUT" ,  1, "<adr>                                   Read  RFChanTREmul PsLUT"              , mainReadRFChanTREmulPsLUT            );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuWPsLUT" ,  2, "<adr val>                               Write RFChanTREmul PsLUT"              , mainWriteRFChanTREmulPsLUT           );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuIPsLUT" ,  3, "<adr nwd val>                           Init  RFChanTREmul PsLUT"              , mainInitRFChanTREmulPsLUT            );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuLPsLUT" ,  0, "                                        Load  RFChanTREmul PsLUT"              , mainLoadRFChanTREmulPsLUT            );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuDPsLUT" ,  0, ""                                                                              , mainDumpRFChanTREmulPsLUT            );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuDPsLUT" ,  1, ""                                                                              , mainDumpRFChanTREmulPsLUT            );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuDPsLUT" ,  2, "[<adr nbit(0, 8-16)>]                   Dump  RFChanTREmul PsLUT"              , mainDumpRFChanTREmulPsLUT            );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuRHwLUT" ,  1, "<adr>                                   Read  RFChanTREmul HwLUT"              , mainReadRFChanTREmulHwLUT            );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuWHwLUT" ,  2, "<adr val>                               Write RFChanTREmul HwLUT"              , mainWriteRFChanTREmulHwLUT           );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuIHwLUT" ,  3, "<adr nwd val>                           Init  RFChanTREmul HwLUT"              , mainInitRFChanTREmulHwLUT            );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuLHwLUT" ,  0, "                                        Load  RFChanTREmul HwLUT"              , mainLoadRFChanTREmulHwLUT            );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuDHwLUT" ,  0, ""                                                                              , mainDumpRFChanTREmulHwLUT            );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuDHwLUT" ,  1, ""                                                                              , mainDumpRFChanTREmulHwLUT            );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuDHwLUT" ,  2, "[<adr nbit(0, 8-16)>]                   Dump  RFChanTREmul HwLUT"              , mainDumpRFChanTREmulHwLUT            );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuRslv"   ,  1, "<reg>                                   Read  RFChanTREmul Slv Reg"            , mainReadRFChanTREmulSlvReg           );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuWslv"   ,  2, "<reg val>                               Write RFChanTREmul Slv Reg"            , mainWriteRFChanTREmulSlvReg          );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuDslv"   ,  0, ""                                                                              , mainDumpRFChanTREmulSlvReg           );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RFChanTREmul Slv Reg"            , mainDumpRFChanTREmulSlvReg           );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuDmp"    ,  0, "                                        Dump  RFChanTREmul State"              , mainDumpRFChanTREmul                 );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , "EmuRst"    ,  0, "                                        Reset RFChanTREmul"                    , mainResetRFChanTREmul                );
    ( void ) shellRegisterCommand( &mainShell, "EMU"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "EMS"  , "EmsRslv"   ,  1, "<reg>                                   Read  RFChanTREmulSw Slv Reg"          , mainReadRFChanTREmulSwSlvReg         );
    ( void ) shellRegisterCommand( &mainShell, "EMS"  , "EmsWslv"   ,  2, "<reg val>                               Write RFChanTREmulSw Slv Reg"          , mainWriteRFChanTREmulSwSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "EMS"  , "EmsDslv"   ,  0, ""                                                                              , mainDumpRFChanTREmulSwSlvReg         );
    ( void ) shellRegisterCommand( &mainShell, "EMS"  , "EmsDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RFChanTREmulSw Slv Reg"          , mainDumpRFChanTREmulSwSlvReg         );
    ( void ) shellRegisterCommand( &mainShell, "EMS"  , "EmsDmp"    ,  0, "                                        Dump  RFChanTREmulSw State"            , mainDumpRFChanTREmulSw               );
    ( void ) shellRegisterCommand( &mainShell, "EMS"  , "EmsRst"    ,  0, "                                        Reset RFChanTREmulSw"                  , mainResetRFChanTREmulSw              );
    ( void ) shellRegisterCommand( &mainShell, "EMS"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "EMF"  , "EmfRslv"   ,  1, "<reg>                                   Read  RFChanTREmulFreqCtr Slv Reg"     , mainReadRFChanTREmulFreqCtrSlvReg    );
    ( void ) shellRegisterCommand( &mainShell, "EMF"  , "EmfWslv"   ,  2, "<reg val>                               Write RFChanTREmulFreqCtr Slv Reg"     , mainWriteRFChanTREmulFreqCtrSlvReg   );
    ( void ) shellRegisterCommand( &mainShell, "EMF"  , "EmfDslv"   ,  0, ""                                                                              , mainDumpRFChanTREmulFreqCtrSlvReg    );
    ( void ) shellRegisterCommand( &mainShell, "EMF"  , "EmfDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RFChanTREmulFreqCtr Slv Reg"     , mainDumpRFChanTREmulFreqCtrSlvReg    );
    ( void ) shellRegisterCommand( &mainShell, "EMF"  , "EmfDmp"    ,  0, "                                        Dump  RFChanTREmulFreqCtr State"       , mainDumpRFChanTREmulFreqCtr          );
    ( void ) shellRegisterCommand( &mainShell, "EMF"  , "EmfRst"    ,  0, "                                        Reset RFChanTREmulFreqCtr"             , mainResetRFChanTREmulFreqCtr         );
    ( void ) shellRegisterCommand( &mainShell, "EMF"  , "EmfRead"   ,  0, "                                        Read  RFChanTREmulFreqCtr"             , mainReadRFChanTREmulFreqCtr          );
    ( void ) shellRegisterCommand( &mainShell, "EMF"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "ACF"  , "AcfRslv"   ,  1, "<reg>                                   Read  AD9364ClkFreqCtr Slv Reg"        , mainReadAD9364ClkFreqCtrSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "ACF"  , "AcfWslv"   ,  2, "<reg val>                               Write AD9364ClkFreqCtr Slv Reg"        , mainWriteAD9364ClkFreqCtrSlvReg      );
    ( void ) shellRegisterCommand( &mainShell, "ACF"  , "AcfDslv"   ,  0, ""                                                                              , mainDumpAD9364ClkFreqCtrSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "ACF"  , "AcfDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  AD9364ClkFreqCtr Slv Reg"        , mainDumpAD9364ClkFreqCtrSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "ACF"  , "AcfDmp"    ,  0, "                                        Dump  AD9364ClkFreqCtr State"          , mainDumpAD9364ClkFreqCtr             );
    ( void ) shellRegisterCommand( &mainShell, "ACF"  , "AcfRst"    ,  0, "                                        Reset AD9364ClkFreqCtr"                , mainResetAD9364ClkFreqCtr            );
    ( void ) shellRegisterCommand( &mainShell, "ACF"  , "AcfRead"   ,  0, "                                        Read  AD9364ClkFreqCtr"                , mainReadAD9364ClkFreqCtr             );
    ( void ) shellRegisterCommand( &mainShell, "ACF"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "ADF"  , "AdfRslv"   ,  1, "<reg>                                   Read  AD9364DACFreqCtr Slv Reg"        , mainReadAD9364DACFreqCtrSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "ADF"  , "AdfWslv"   ,  2, "<reg val>                               Write AD9364DACFreqCtr Slv Reg"        , mainWriteAD9364DACFreqCtrSlvReg      );
    ( void ) shellRegisterCommand( &mainShell, "ADF"  , "AdfDslv"   ,  0, ""                                                                              , mainDumpAD9364DACFreqCtrSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "ADF"  , "AdfDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  AD9364DACFreqCtr Slv Reg"        , mainDumpAD9364DACFreqCtrSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "ADF"  , "AdfDmp"    ,  0, "                                        Dump  AD9364DACFreqCtr State"          , mainDumpAD9364DACFreqCtr             );
    ( void ) shellRegisterCommand( &mainShell, "ADF"  , "AdfRst"    ,  0, "                                        Reset AD9364DACFreqCtr"                , mainResetAD9364DACFreqCtr            );
    ( void ) shellRegisterCommand( &mainShell, "ADF"  , "AdfRead"   ,  0, "                                        Read  AD9364DACFreqCtr"                , mainReadAD9364DACFreqCtr             );
    ( void ) shellRegisterCommand( &mainShell, "ADF"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "AAF"  , "AafRslv"   ,  1, "<reg>                                   Read  AD9364ADCFreqCtr Slv Reg"        , mainReadAD9364ADCFreqCtrSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "AAF"  , "AafWslv"   ,  2, "<reg val>                               Write AD9364ADCFreqCtr Slv Reg"        , mainWriteAD9364ADCFreqCtrSlvReg      );
    ( void ) shellRegisterCommand( &mainShell, "AAF"  , "AafDslv"   ,  0, ""                                                                              , mainDumpAD9364ADCFreqCtrSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "AAF"  , "AafDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  AD9364ADCFreqCtr Slv Reg"        , mainDumpAD9364ADCFreqCtrSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "AAF"  , "AafDmp"    ,  0, "                                        Dump  AD9364ADCFreqCtr State"          , mainDumpAD9364ADCFreqCtr             );
    ( void ) shellRegisterCommand( &mainShell, "AAF"  , "AafRst"    ,  0, "                                        Reset AD9364ADCFreqCtr"                , mainResetAD9364ADCFreqCtr            );
    ( void ) shellRegisterCommand( &mainShell, "AAF"  , "AafRead"   ,  0, "                                        Read  AD9364ADCFreqCtr"                , mainReadAD9364ADCFreqCtr             );
    ( void ) shellRegisterCommand( &mainShell, "AAF"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "NSD"  , "NsdRslv"   ,  1, "<reg>                                   Read  RxNSDet Slv Reg"                 , mainReadRxNSDetSlvReg                );
    ( void ) shellRegisterCommand( &mainShell, "NSD"  , "NsdWslv"   ,  2, "<reg val>                               Write RxNSDet Slv Reg"                 , mainWriteRxNSDetSlvReg               );
    ( void ) shellRegisterCommand( &mainShell, "NSD"  , "NsdDslv"   ,  0, ""                                                                              , mainDumpRxNSDetSlvReg                );
    ( void ) shellRegisterCommand( &mainShell, "NSD"  , "NsdDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxNSDet Slv Reg"                 , mainDumpRxNSDetSlvReg                );
    ( void ) shellRegisterCommand( &mainShell, "NSD"  , "NsdDmp"    ,  0, "                                        Dump  RxNSDet State"                   , mainDumpRxNSDet                      );
    ( void ) shellRegisterCommand( &mainShell, "NSD"  , "NsdRst"    ,  0, "                                        Reset RxNSDet"                         , mainResetRxNSDet                     );
    ( void ) shellRegisterCommand( &mainShell, "NSD"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "DSK"  , "DskRBram"  ,  1, "<adr>                                   Read  RxTddAXISink Bram"               , mainReadRxTddAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "DSK"  , "DskWBram"  ,  2, "<adr val>                               Write RxTddAXISink Bram"               , mainWriteRxTddAXISinkBram            );
    ( void ) shellRegisterCommand( &mainShell, "DSK"  , "DskIBram"  ,  3, "<adr nwd val>                           Init  RxTddAXISink Bram"               , mainInitRxTddAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "DSK"  , "DskDBram"  ,  0, ""                                                                              , mainDumpRxTddAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "DSK"  , "DskDBram"  ,  1, ""                                                                              , mainDumpRxTddAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "DSK"  , "DskDBram"  ,  2, "[<adr nbit(0, 8-16)>]                   Dump  RxTddAXISink Bram"               , mainDumpRxTddAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "DSK"  , "DskRslv"   ,  1, "<reg>                                   Read  RxTddAXISink Slv Reg"            , mainReadRxTddAXISinkSlvReg           );
    ( void ) shellRegisterCommand( &mainShell, "DSK"  , "DskWslv"   ,  2, "<reg val>                               Write RxTddAXISink Slv Reg"            , mainWriteRxTddAXISinkSlvReg          );
    ( void ) shellRegisterCommand( &mainShell, "DSK"  , "DskDslv"   ,  0, ""                                                                              , mainDumpRxTddAXISinkSlvReg           );
    ( void ) shellRegisterCommand( &mainShell, "DSK"  , "DskDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxTddAXISink Slv Reg"            , mainDumpRxTddAXISinkSlvReg           );
    ( void ) shellRegisterCommand( &mainShell, "DSK"  , "DskDmp"    ,  0, "                                        Dump  RxTddAXISink State"              , mainDumpRxTddAXISink                 );
    ( void ) shellRegisterCommand( &mainShell, "DSK"  , "DskRst"    ,  0, "                                        Reset RxTddAXISink"                    , mainResetRxTddAXISink                );
    ( void ) shellRegisterCommand( &mainShell, "DSK"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "PRS"  , "PrsRBram"  ,  1, "<adr>                                   Read  RxPrsAXISink Bram"               , mainReadRxPrsAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "PRS"  , "PrsWBram"  ,  2, "<adr val>                               Write RxPrsAXISink Bram"               , mainWriteRxPrsAXISinkBram            );
    ( void ) shellRegisterCommand( &mainShell, "PRS"  , "PrsIBram"  ,  3, "<adr nwd val>                           Init  RxPrsAXISink Bram"               , mainInitRxPrsAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "PRS"  , "PrsDBram"  ,  0, ""                                                                              , mainDumpRxPrsAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "PRS"  , "PrsDBram"  ,  1, ""                                                                              , mainDumpRxPrsAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "PRS"  , "PrsDBram"  ,  2, "[<adr nbit(0, 8-16)>]                   Dump  RxPrsAXISink Bram"               , mainDumpRxPrsAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "PRS"  , "PrsRslv"   ,  1, "<reg>                                   Read  RxPrsAXISink Slv Reg"            , mainReadRxPrsAXISinkSlvReg           );
    ( void ) shellRegisterCommand( &mainShell, "PRS"  , "PrsWslv"   ,  2, "<reg val>                               Write RxPrsAXISink Slv Reg"            , mainWriteRxPrsAXISinkSlvReg          );
    ( void ) shellRegisterCommand( &mainShell, "PRS"  , "PrsDslv"   ,  0, ""                                                                              , mainDumpRxPrsAXISinkSlvReg           );
    ( void ) shellRegisterCommand( &mainShell, "PRS"  , "PrsDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxPrsAXISink Slv Reg"            , mainDumpRxPrsAXISinkSlvReg           );
    ( void ) shellRegisterCommand( &mainShell, "PRS"  , "PrsDmp"    ,  0, "                                        Dump  RxPrsAXISink State"              , mainDumpRxPrsAXISink                 );
    ( void ) shellRegisterCommand( &mainShell, "PRS"  , "PrsRst"    ,  0, "                                        Reset RxPrsAXISink"                    , mainResetRxPrsAXISink                );
    ( void ) shellRegisterCommand( &mainShell, "PRS"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "DTA"  , "DtaRBram"  ,  1, "<adr>                                   Read  RxDtaAXISink Bram"               , mainReadRxDtaAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "DTA"  , "DtaWBram"  ,  2, "<adr val>                               Write RxDtaAXISink Bram"               , mainWriteRxDtaAXISinkBram            );
    ( void ) shellRegisterCommand( &mainShell, "DTA"  , "DtaIBram"  ,  3, "<adr nwd val>                           Init  RxDtaAXISink Bram"               , mainInitRxDtaAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "DTA"  , "DtaDBram"  ,  0, ""                                                                              , mainDumpRxDtaAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "DTA"  , "DtaDBram"  ,  1, ""                                                                              , mainDumpRxDtaAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "DTA"  , "DtaDBram"  ,  2, "[<adr nbit(0, 8-16)>]                   Dump  RxDtaAXISink Bram"               , mainDumpRxDtaAXISinkBram             );
    ( void ) shellRegisterCommand( &mainShell, "DTA"  , "DtaRslv"   ,  1, "<reg>                                   Read  RxDtaAXISink Slv Reg"            , mainReadRxDtaAXISinkSlvReg           );
    ( void ) shellRegisterCommand( &mainShell, "DTA"  , "DtaWslv"   ,  2, "<reg val>                               Write RxDtaAXISink Slv Reg"            , mainWriteRxDtaAXISinkSlvReg          );
    ( void ) shellRegisterCommand( &mainShell, "DTA"  , "DtaDslv"   ,  0, ""                                                                              , mainDumpRxDtaAXISinkSlvReg           );
    ( void ) shellRegisterCommand( &mainShell, "DTA"  , "DtaDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxDtaAXISink Slv Reg"            , mainDumpRxDtaAXISinkSlvReg           );
    ( void ) shellRegisterCommand( &mainShell, "DTA"  , "DtaDmp"    ,  0, "                                        Dump  RxDtaAXISink State"              , mainDumpRxDtaAXISink                 );
    ( void ) shellRegisterCommand( &mainShell, "DTA"  , "DtaRst"    ,  0, "                                        Reset RxDtaAXISink"                    , mainResetRxDtaAXISink                );
    ( void ) shellRegisterCommand( &mainShell, "DTA"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "A00"  , "A00RBram"  ,  1, "<adr>                                   Read  RxNsdA00AXISink Bram"            , mainReadRxNsdA00AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A00"  , "A00WBram"  ,  2, "<adr val>                               Write RxNsdA00AXISink Bram"            , mainWriteRxNsdA00AXISinkBram         );
    ( void ) shellRegisterCommand( &mainShell, "A00"  , "A00IBram"  ,  3, "<adr nwd val>                           Init  RxNsdA00AXISink Bram"            , mainInitRxNsdA00AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A00"  , "A00DBram"  ,  0, ""                                                                              , mainDumpRxNsdA00AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A00"  , "A00DBram"  ,  1, ""                                                                              , mainDumpRxNsdA00AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A00"  , "A00DBram"  ,  2, "[<adr nbit(0, 8-16)>]                   Dump  RxNsdA00AXISink Bram"            , mainDumpRxNsdA00AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A00"  , "A00Rslv"   ,  1, "<reg>                                   Read  RxNsdA00AXISink Slv Reg"         , mainReadRxNsdA00AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "A00"  , "A00Wslv"   ,  2, "<reg val>                               Write RxNsdA00AXISink Slv Reg"         , mainWriteRxNsdA00AXISinkSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "A00"  , "A00Dslv"   ,  0, ""                                                                              , mainDumpRxNsdA00AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "A00"  , "A00Dslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxNsdA00AXISink Slv Reg"         , mainDumpRxNsdA00AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "A00"  , "A00Dmp"    ,  0, "                                        Dump  RxNsdA00AXISink State"           , mainDumpRxNsdA00AXISink              );
    ( void ) shellRegisterCommand( &mainShell, "A00"  , "A00Rst"    ,  0, "                                        Reset RxNsdA00AXISink"                 , mainResetRxNsdA00AXISink             );
    ( void ) shellRegisterCommand( &mainShell, "A00"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "A01"  , "A01RBram"  ,  1, "<adr>                                   Read  RxNsdA01AXISink Bram"            , mainReadRxNsdA01AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A01"  , "A01WBram"  ,  2, "<adr val>                               Write RxNsdA01AXISink Bram"            , mainWriteRxNsdA01AXISinkBram         );
    ( void ) shellRegisterCommand( &mainShell, "A01"  , "A01IBram"  ,  3, "<adr nwd val>                           Init  RxNsdA01AXISink Bram"            , mainInitRxNsdA01AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A01"  , "A01DBram"  ,  0, ""                                                                              , mainDumpRxNsdA01AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A01"  , "A01DBram"  ,  1, ""                                                                              , mainDumpRxNsdA01AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A01"  , "A01DBram"  ,  2, "[<adr nbit(0, 8-16)>]                   Dump  RxNsdA01AXISink Bram"            , mainDumpRxNsdA01AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A01"  , "A01Rslv"   ,  1, "<reg>                                   Read  RxNsdA01AXISink Slv Reg"         , mainReadRxNsdA01AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "A01"  , "A01Wslv"   ,  2, "<reg val>                               Write RxNsdA01AXISink Slv Reg"         , mainWriteRxNsdA01AXISinkSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "A01"  , "A01Dslv"   ,  0, ""                                                                              , mainDumpRxNsdA01AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "A01"  , "A01Dslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxNsdA01AXISink Slv Reg"         , mainDumpRxNsdA01AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "A01"  , "A01Dmp"    ,  0, "                                        Dump  RxNsdA01AXISink State"           , mainDumpRxNsdA01AXISink              );
    ( void ) shellRegisterCommand( &mainShell, "A01"  , "A01Rst"    ,  0, "                                        Reset RxNsdA01AXISink"                 , mainResetRxNsdA01AXISink             );
    ( void ) shellRegisterCommand( &mainShell, "A01"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "A15"  , "A15RBram"  ,  1, "<adr>                                   Read  RxNsdA15AXISink Bram"            , mainReadRxNsdA15AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A15"  , "A15WBram"  ,  2, "<adr val>                               Write RxNsdA15AXISink Bram"            , mainWriteRxNsdA15AXISinkBram         );
    ( void ) shellRegisterCommand( &mainShell, "A15"  , "A15IBram"  ,  3, "<adr nwd val>                           Init  RxNsdA15AXISink Bram"            , mainInitRxNsdA15AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A15"  , "A15DBram"  ,  0, ""                                                                              , mainDumpRxNsdA15AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A15"  , "A15DBram"  ,  1, ""                                                                              , mainDumpRxNsdA15AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A15"  , "A15DBram"  ,  2, "[<adr nbit(0, 8-16)>]                   Dump  RxNsdA15AXISink Bram"            , mainDumpRxNsdA15AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "A15"  , "A15Rslv"   ,  1, "<reg>                                   Read  RxNsdA15AXISink Slv Reg"         , mainReadRxNsdA15AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "A15"  , "A15Wslv"   ,  2, "<reg val>                               Write RxNsdA15AXISink Slv Reg"         , mainWriteRxNsdA15AXISinkSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "A15"  , "A15Dslv"   ,  0, ""                                                                              , mainDumpRxNsdA15AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "A15"  , "A15Dslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxNsdA15AXISink Slv Reg"         , mainDumpRxNsdA15AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "A15"  , "A15Dmp"    ,  0, "                                        Dump  RxNsdA15AXISink State"           , mainDumpRxNsdA15AXISink              );
    ( void ) shellRegisterCommand( &mainShell, "A15"  , "A15Rst"    ,  0, "                                        Reset RxNsdA15AXISink"                 , mainResetRxNsdA15AXISink             );
    ( void ) shellRegisterCommand( &mainShell, "A15"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "CSK"  , "CskRBram"  ,  1, "<adr>                                   Read  RxNsdCordicAXISink Bram"         , mainReadRxNsdCordicAXISinkBram       );
    ( void ) shellRegisterCommand( &mainShell, "CSK"  , "CskWBram"  ,  2, "<adr val>                               Write RxNsdCordicAXISink Bram"         , mainWriteRxNsdCordicAXISinkBram      );
    ( void ) shellRegisterCommand( &mainShell, "CSK"  , "CskIBram"  ,  3, "<adr nwd val>                           Init  RxNsdCordicAXISink Bram"         , mainInitRxNsdCordicAXISinkBram       );
    ( void ) shellRegisterCommand( &mainShell, "CSK"  , "CskDBram"  ,  0, ""                                                                              , mainDumpRxNsdCordicAXISinkBram       );
    ( void ) shellRegisterCommand( &mainShell, "CSK"  , "CskDBram"  ,  1, ""                                                                              , mainDumpRxNsdCordicAXISinkBram       );
    ( void ) shellRegisterCommand( &mainShell, "CSK"  , "CskDBram"  ,  2, "[<adr nbit(0, 8-16)>]                   Dump  RxNsdCordicAXISink Bram"         , mainDumpRxNsdCordicAXISinkBram       );
    ( void ) shellRegisterCommand( &mainShell, "CSK"  , "CskRslv"   ,  1, "<reg>                                   Read  RxNsdCordicAXISink Slv Reg"      , mainReadRxNsdCordicAXISinkSlvReg     );
    ( void ) shellRegisterCommand( &mainShell, "CSK"  , "CskWslv"   ,  2, "<reg val>                               Write RxNsdCordicAXISink Slv Reg"      , mainWriteRxNsdCordicAXISinkSlvReg    );
    ( void ) shellRegisterCommand( &mainShell, "CSK"  , "CskDslv"   ,  0, ""                                                                              , mainDumpRxNsdCordicAXISinkSlvReg     );
    ( void ) shellRegisterCommand( &mainShell, "CSK"  , "CskDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxNsdCordicAXISink Slv Reg"      , mainDumpRxNsdCordicAXISinkSlvReg     );
    ( void ) shellRegisterCommand( &mainShell, "CSK"  , "CskDmp"    ,  0, "                                        Dump  RxNsdCordicAXISink State"        , mainDumpRxNsdCordicAXISink           );
    ( void ) shellRegisterCommand( &mainShell, "CSK"  , "CskRst"    ,  0, "                                        Reset RxNsdCordicAXISink"              , mainResetRxNsdCordicAXISink          );
    ( void ) shellRegisterCommand( &mainShell, "CSK"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "FSK"  , "FskRBram"  ,  1, "<adr>                                   Read  RxNsdFFTAXISink Bram"            , mainReadRxNsdFFTAXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "FSK"  , "FskWBram"  ,  2, "<adr val>                               Write RxNsdFFTAXISink Bram"            , mainWriteRxNsdFFTAXISinkBram         );
    ( void ) shellRegisterCommand( &mainShell, "FSK"  , "FskIBram"  ,  3, "<adr nwd val>                           Init  RxNsdFFTAXISink Bram"            , mainInitRxNsdFFTAXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "FSK"  , "FskDBram"  ,  0, ""                                                                              , mainDumpRxNsdFFTAXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "FSK"  , "FskDBram"  ,  1, ""                                                                              , mainDumpRxNsdFFTAXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "FSK"  , "FskDBram"  ,  2, "[<adr nbit(0, 8-16)>]                   Dump  RxNsdFFTAXISink Bram"            , mainDumpRxNsdFFTAXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "FSK"  , "FskRslv"   ,  1, "<reg>                                   Read  RxNsdFFTAXISink Slv Reg"         , mainReadRxNsdFFTAXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "FSK"  , "FskWslv"   ,  2, "<reg val>                               Write RxNsdFFTAXISink Slv Reg"         , mainWriteRxNsdFFTAXISinkSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "FSK"  , "FskDslv"   ,  0, ""                                                                              , mainDumpRxNsdFFTAXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "FSK"  , "FskDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxNsdFFTAXISink Slv Reg"         , mainDumpRxNsdFFTAXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "FSK"  , "FskDmp"    ,  0, "                                        Dump  RxNsdFFTAXISink State"           , mainDumpRxNsdFFTAXISink              );
    ( void ) shellRegisterCommand( &mainShell, "FSK"  , "FskRst"    ,  0, "                                        Reset RxNsdFFTAXISink"                 , mainResetRxNsdFFTAXISink             );
    ( void ) shellRegisterCommand( &mainShell, "FSK"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "B00"  , "B00RBram"  ,  1, "<adr>                                   Read  RxNsdB00AXISink Bram"            , mainReadRxNsdB00AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B00"  , "B00WBram"  ,  2, "<adr val>                               Write RxNsdB00AXISink Bram"            , mainWriteRxNsdB00AXISinkBram         );
    ( void ) shellRegisterCommand( &mainShell, "B00"  , "B00IBram"  ,  3, "<adr nwd val>                           Init  RxNsdB00AXISink Bram"            , mainInitRxNsdB00AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B00"  , "B00DBram"  ,  0, ""                                                                              , mainDumpRxNsdB00AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B00"  , "B00DBram"  ,  1, ""                                                                              , mainDumpRxNsdB00AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B00"  , "B00DBram"  ,  2, "[<adr nbit(0, 8-16)>]                   Dump  RxNsdB00AXISink Bram"            , mainDumpRxNsdB00AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B00"  , "B00Rslv"   ,  1, "<reg>                                   Read  RxNsdB00AXISink Slv Reg"         , mainReadRxNsdB00AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "B00"  , "B00Wslv"   ,  2, "<reg val>                               Write RxNsdB00AXISink Slv Reg"         , mainWriteRxNsdB00AXISinkSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "B00"  , "B00Dslv"   ,  0, ""                                                                              , mainDumpRxNsdB00AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "B00"  , "B00Dslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxNsdB00AXISink Slv Reg"         , mainDumpRxNsdB00AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "B00"  , "B00Dmp"    ,  0, "                                        Dump  RxNsdB00AXISink State"           , mainDumpRxNsdB00AXISink              );
    ( void ) shellRegisterCommand( &mainShell, "B00"  , "B00Rst"    ,  0, "                                        Reset RxNsdB00AXISink"                 , mainResetRxNsdB00AXISink             );
    ( void ) shellRegisterCommand( &mainShell, "B00"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "B01"  , "B01RBram"  ,  1, "<adr>                                   Read  RxNsdB01AXISink Bram"            , mainReadRxNsdB01AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B01"  , "B01WBram"  ,  2, "<adr val>                               Write RxNsdB01AXISink Bram"            , mainWriteRxNsdB01AXISinkBram         );
    ( void ) shellRegisterCommand( &mainShell, "B01"  , "B01IBram"  ,  3, "<adr nwd val>                           Init  RxNsdB01AXISink Bram"            , mainInitRxNsdB01AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B01"  , "B01DBram"  ,  0, ""                                                                              , mainDumpRxNsdB01AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B01"  , "B01DBram"  ,  1, ""                                                                              , mainDumpRxNsdB01AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B01"  , "B01DBram"  ,  2, "[<adr nbit(0, 8-16)>]                   Dump  RxNsdB01AXISink Bram"            , mainDumpRxNsdB01AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B01"  , "B01Rslv"   ,  1, "<reg>                                   Read  RxNsdB01AXISink Slv Reg"         , mainReadRxNsdB01AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "B01"  , "B01Wslv"   ,  2, "<reg val>                               Write RxNsdB01AXISink Slv Reg"         , mainWriteRxNsdB01AXISinkSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "B01"  , "B01Dslv"   ,  0, ""                                                                              , mainDumpRxNsdB01AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "B01"  , "B01Dslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxNsdB01AXISink Slv Reg"         , mainDumpRxNsdB01AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "B01"  , "B01Dmp"    ,  0, "                                        Dump  RxNsdB01AXISink State"           , mainDumpRxNsdB01AXISink              );
    ( void ) shellRegisterCommand( &mainShell, "B01"  , "B01Rst"    ,  0, "                                        Reset RxNsdB01AXISink"                 , mainResetRxNsdB01AXISink             );
    ( void ) shellRegisterCommand( &mainShell, "B01"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "B15"  , "B15RBram"  ,  1, "<adr>                                   Read  RxNsdB15AXISink Bram"            , mainReadRxNsdB15AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B15"  , "B15WBram"  ,  2, "<adr val>                               Write RxNsdB15AXISink Bram"            , mainWriteRxNsdB15AXISinkBram         );
    ( void ) shellRegisterCommand( &mainShell, "B15"  , "B15IBram"  ,  3, "<adr nwd val>                           Init  RxNsdB15AXISink Bram"            , mainInitRxNsdB15AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B15"  , "B15DBram"  ,  0, ""                                                                              , mainDumpRxNsdB15AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B15"  , "B15DBram"  ,  1, ""                                                                              , mainDumpRxNsdB15AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B15"  , "B15DBram"  ,  2, "[<adr nbit(0, 8-16)>]                   Dump  RxNsdB15AXISink Bram"            , mainDumpRxNsdB15AXISinkBram          );
    ( void ) shellRegisterCommand( &mainShell, "B15"  , "B15Rslv"   ,  1, "<reg>                                   Read  RxNsdB15AXISink Slv Reg"         , mainReadRxNsdB15AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "B15"  , "B15Wslv"   ,  2, "<reg val>                               Write RxNsdB15AXISink Slv Reg"         , mainWriteRxNsdB15AXISinkSlvReg       );
    ( void ) shellRegisterCommand( &mainShell, "B15"  , "B15Dslv"   ,  0, ""                                                                              , mainDumpRxNsdB15AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "B15"  , "B15Dslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxNsdB15AXISink Slv Reg"         , mainDumpRxNsdB15AXISinkSlvReg        );
    ( void ) shellRegisterCommand( &mainShell, "B15"  , "B15Dmp"    ,  0, "                                        Dump  RxNsdB15AXISink State"           , mainDumpRxNsdB15AXISink              );
    ( void ) shellRegisterCommand( &mainShell, "B15"  , "B15Rst"    ,  0, "                                        Reset RxNsdB15AXISink"                 , mainResetRxNsdB15AXISink             );
    ( void ) shellRegisterCommand( &mainShell, "B15"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRRBramFFT",  1, "<adr>                                   Read  RxPrsCIR BramFFT"                , mainReadRxPrsCIRBramFFT              );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRWBramFFT",  2, "<adr val>                               Write RxPrsCIR BramFFT"                , mainWriteRxPrsCIRBramFFT             );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRIBramFFT",  3, "<adr nwd val>                           Init  RxPrsCIR BramFFT"                , mainInitRxPrsCIRBramFFT              );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRDBramFFT",  0, ""                                                                              , mainDumpRxPrsCIRBramFFT              );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRDBramFFT",  1, ""                                                                              , mainDumpRxPrsCIRBramFFT              );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRDBramFFT",  2, "[<adr nbit(0, 8-16)>]                   Dump  RxPrsCIR BramFFT"                , mainDumpRxPrsCIRBramFFT              );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRRBramABS",  1, "<adr>                                   Read  RxPrsCIR BramABS"                , mainReadRxPrsCIRBramABS              );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRWBramABS",  2, "<adr val>                               Write RxPrsCIR BramABS"                , mainWriteRxPrsCIRBramABS             );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRIBramABS",  3, "<adr nwd val>                           Init  RxPrsCIR BramABS"                , mainInitRxPrsCIRBramABS              );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRDBramABS",  0, ""                                                                              , mainDumpRxPrsCIRBramABS              );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRDBramABS",  1, ""                                                                              , mainDumpRxPrsCIRBramABS              );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRDBramABS",  2, "[<adr nbit(0, 8-16)>]                   Dump  RxPrsCIR BramABS"                , mainDumpRxPrsCIRBramABS              );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRRslv"   ,  1, "<reg>                                   Read  RxPrsCIR Slv Reg"                , mainReadRxPrsCIRSlvReg               );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRWslv"   ,  2, "<reg val>                               Write RxPrsCIR Slv Reg"                , mainWriteRxPrsCIRSlvReg              );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRDslv"   ,  0, ""                                                                              , mainDumpRxPrsCIRSlvReg               );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRDslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxPrsCIR Slv Reg"                , mainDumpRxPrsCIRSlvReg               );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRDmp"    ,  0, "                                        Dump  RxPrsCIR State"                  , mainDumpRxPrsCIR                     );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRRst"    ,  0, "                                        Reset RxPrsCIR"                        , mainResetRxPrsCIR                    );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , "CIRDelta"  ,  0, "                                        RxPrsCIR Calc Deltas"                  , mainRxPrsCIRCalcDelta                );
    ( void ) shellRegisterCommand( &mainShell, "CIR"  , ""          ,  0, "", NULL );
    ( void ) shellRegisterCommand( &mainShell, "BPA"  , "BPARslv"   ,  1, "<reg>                                   Read  RxPrsBPA Slv Reg"                , mainReadRxPrsBPASlvReg               );
    ( void ) shellRegisterCommand( &mainShell, "BPA"  , "BPAWslv"   ,  2, "<reg val>                               Write RxPrsBPA Slv Reg"                , mainWriteRxPrsBPASlvReg              );
    ( void ) shellRegisterCommand( &mainShell, "BPA"  , "BPADslv"   ,  0, ""                                                                              , mainDumpRxPrsBPASlvReg               );
    ( void ) shellRegisterCommand( &mainShell, "BPA"  , "BPADslv"   ,  1, "[<fmt(0=hex 1=bin)>]                    Dump  RxPrsBPA Slv Reg"                , mainDumpRxPrsBPASlvReg               );
    ( void ) shellRegisterCommand( &mainShell, "BPA"  , "BPADmp"    ,  0, "                                        Dump  RxPrsBPA State"                  , mainDumpRxPrsBPA                     );
    ( void ) shellRegisterCommand( &mainShell, "BPA"  , "BPARst"    ,  0, "                                        Reset RxPrsBPA"                        , mainResetRxPrsBPA                    );
    ( void ) shellRegisterCommand( &mainShell, "BPA"  , "BPADelta"  ,  0, "                                        RxPrsBPA Calc Deltas"                  , mainRxPrsBPACalcDelta                );
    ( void ) shellRegisterCommand( &mainShell, "BPA"  , ""          ,  0, "", NULL );
//===========================================
//////// End of script-generated code ///////
//===========================================
